/// Flutter icons Moim
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Moim
///      fonts:
///       - asset: fonts/Moim.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Moim {
  Moim._();

  static const _kFontFam = 'Moim';
  static const _kFontPkg = null;

  static const IconData community_icon__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_icon_01 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon_01 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icon_01 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_icon_01 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley_face_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
